setwd("~/PycharmProjects/STAT8002/r/data")
corn = read.csv('CORN.csv')
soybean=read.csv('SOYBEAN.csv')
wheat=read.csv('WHEAT.csv')
rice=read.csv('RICE.csv')
oat=read.csv('OAT.csv')

fit_corn=lm(Price~Price.T.1+headline_positiveness+headline_negativeness,data=corn)
fit_soybean=lm(Price~Price.T.1+headline_positiveness+headline_negativeness,data=soybean)
fit_wheat=lm(Price~Price.T.1+headline_positiveness+headline_negativeness,data=wheat)
fit_rice=lm(Price~Price.T.1+headline_positiveness+headline_negativeness,data=rice)
fit_oat=lm(Price~Price.T.1+headline_positiveness+headline_negativeness,data=oat)

fit_corn=lm(Price~Price.T.1+content_positiveness+content_negativeness,data=corn)
fit_soybean=lm(Price~Price.T.1+content_positiveness+content_negativeness,data=soybean)
fit_wheat=lm(Price~Price.T.1+content_positiveness+content_negativeness,data=wheat)
fit_rice=lm(Price~Price.T.1+content_positiveness+content_negativeness,data=rice)
fit_oat=lm(Price~Price.T.1+content_positiveness+content_negativeness,data=oat)

fit_corn_null=lm(Price~Price.T.1,data=corn)
fit_soybean_null=lm(Price~Price.T.1,data=soybean)
fit_wheat_null=lm(Price~Price.T.1,data=wheat)
fit_rice_null=lm(Price~Price.T.1,data=rice)
fit_oat_null=lm(Price~Price.T.1,data=oat)